Style/AsciiComments:
  Enabled: false
Metrics/LineLength:
  Max: 120
Documentation:
  Enabled: false
Style/ClassAndModuleChildren:
  SupportedStyles:
    - nested
    - compact
SingleSpaceBeforeFirstArg:
  Enabled: false

AllCops:
  Includes:
    - Gemfile
    - Rakefile
  Excludes:
    - bin/**
    - vendor/**
    - .bundle/**

SymbolArray:
  Enabled: true

CollectionMethods:
  PreferredMethods:
    collect: 'map'
    inject: 'reduce'
    detect: 'find'
    find_all: 'select'

SpaceInsideHashLiteralBraces:
  EnforcedStyleIsWithSpaces: false

